identifier: qhws42v2_nrf52840_left
name: qhws42v2_nrf52840_left
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
