# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: qhws42v3_nrf52840_left
    shield: "qhws42v3_left"
  - board: qhws42v3_nrf52840_right
    shield: "qhws42v3_right"
  # - board: qhws42v2_nrf52840_left
  #   shield: "qhws42v2_left"
  # - board: qhws42v2_nrf52840_right
  #   shield: "qhws42v2_right"
  # - board: qhws42v3_nrf52840_left
  #   shield: "settings_reset"
  - board: qhws42v3_nrf52840_right
    shield: "settings_reset"
