identifier: qhws42v3_nrf52840_r
name: qhws42v3_nrf52840_r
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
