manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: jsenjobs
      url-base: https://github.com/jsenjobs
  projects:
    - name: zmk
      path: zmk
      remote: jsenjobs
      revision: mouse_ps2_v2_scroll
      import: app/west.yml
    # - name: zmk
    #   remote: infused-kim
    #   revision: pr-testing/mouse_ps2_v2
    #   import: app/west.yml
  self:
    path: config
